apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- clusterissuer.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: cloudflare-api-token
  namespace: cert-manager
  envs:
  - token.env