apiVersion: v1
kind: Pod
metadata:
  annotations:
    tke.cloud.tencent.com/networks: "tke-route-eni"
    tke.cloud.tencent.com/eip-attributes: ""
  labels:
    app: busybox-eip
  name: busybox-eip
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - command: ["sleep", "2300000"]
    image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    resources:
      requests:
        tke.cloud.tencent.com/eni-ip: "1"
        tke.cloud.tencent.com/eip: "1"
      limits:
        tke.cloud.tencent.com/eni-ip: "1"
        tke.cloud.tencent.com/eip: "1"