apiVersion: v1
kind: Pod
metadata:
  annotations:
    tke.cloud.tencent.com/networks: "tke-route-eni"
    tke.cloud.tencent.com/vpc-ip-claim-delete-policy: "Never"
  labels:
    app: mysql
  name: mysql
spec:
  containers:
  - image: mysql:5.6
    imagePullPolicy: IfNotPresent
    name: mysql
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: root
    ports:
    - containerPort: 3306
      name: mysql
    resources:
      requests:
        tke.cloud.tencent.com/eni-ip: "1"
      limits:
        tke.cloud.tencent.com/eni-ip: "1"