apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/traefik/configuration
- ../../base/monitoring
- grafana-dashboard
- prometheus-dashboard
- alertmanager-dashboard

secretGenerator:
- name: monitoring-auth
  namespace: monitoring
  envs:
  - users.env

resources:
- monitoring-basicauth-middleware.yaml