apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/traefik/chart
- ../../base/traefik/configuration

resources:
- traefik-basicauth-middleware.yaml
- traefik-cert.yaml
- traefik-ingressroute.yaml

namespace: traefik
namePrefix: "roc-"

secretGenerator:
- name: traefik-auth
  envs:
  - users.env