apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus-clusterRole.yaml
- prometheus-clusterRoleBinding.yaml
- prometheus-operator-0alertmanagerCustomResourceDefinition.yaml
- prometheus-operator-0podmonitorCustomResourceDefinition.yaml
- prometheus-operator-0prometheusCustomResourceDefinition.yaml
- prometheus-operator-0prometheusruleCustomResourceDefinition.yaml
- prometheus-operator-0servicemonitorCustomResourceDefinition.yaml
- prometheus-operator-0thanosrulerCustomResourceDefinition.yaml
- prometheus-operator-clusterRole.yaml
- prometheus-operator-clusterRoleBinding.yaml
- prometheus-operator-deployment.yaml
- prometheus-operator-service.yaml
- prometheus-operator-serviceAccount.yaml
- prometheus-operator-serviceMonitor.yaml
- prometheus-prometheus.yaml
- prometheus-roleBindingConfig.yaml
- prometheus-roleBindingSpecificNamespaces.yaml
- prometheus-roleConfig.yaml
- prometheus-roleSpecificNamespaces.yaml
- prometheus-rules.yaml
- prometheus-service.yaml
- prometheus-serviceAccount.yaml
- prometheus-serviceMonitor.yaml
- prometheus-serviceMonitorApiserver.yaml
- prometheus-serviceMonitorCoreDNS.yaml
- prometheus-serviceMonitorKubeControllerManager.yaml
- prometheus-serviceMonitorKubeScheduler.yaml
- prometheus-serviceMonitorKubelet.yaml